"""empty message

Revision ID: 79573b431051
Revises: 219742eecdfa
Create Date: 2023-12-17 21:16:02.339427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79573b431051'
down_revision = '219742eecdfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('image_URL',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.alter_column('image_URL',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
